# Task 1
# Data Exploration and Enrichment

 1. Import Libraries

In [23]:
# =====================================================
# Load Required Libraries
# =====================================================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)

plt.style.use("ggplot")

2. Define Paths

In [32]:
RAW_DATA = Path("../data/raw")

excel_file = RAW_DATA / "ethiopia_fi_unified_data.xlsx"

df = pd.read_excel(
    excel_file,
    sheet_name="ethiopia_fi_unified_data"
)

impact_links = pd.read_excel(
    excel_file,
    sheet_name="Impact_sheet"
)

reference = pd.read_csv(
    RAW_DATA / "reference_codes.csv"
)

In [40]:
print(df.shape)
print(impact_links.shape)
print(reference.shape)

(43, 34)
(14, 35)
(71, 4)

3. Load Dataset

In [41]:
import pandas as pd

excel_file = "../data/raw/ethiopia_fi_unified_data.xlsx"

xls = pd.ExcelFile(excel_file)

print(xls.sheet_names)

['ethiopia_fi_unified_data', 'Impact_sheet']

In [42]:
excel_file = "../data/raw/ethiopia_fi_unified_data.xlsx"

# Main data sheet
df = pd.read_excel(
    excel_file,
    sheet_name="ethiopia_fi_unified_data"
)

# Impact links sheet
impact_links = pd.read_excel(
    excel_file,
    sheet_name="Impact_sheet"
)

# Reference codes
reference = pd.read_csv("../data/raw/reference_codes.csv")

In [43]:
print("Main Dataset Shape:", df.shape)
print("Impact Links Shape:", impact_links.shape)
print("Reference Codes Shape:", reference.shape)

Main Dataset Shape: (43, 34)
Impact Links Shape: (14, 35)
Reference Codes Shape: (71, 4)

In [44]:
df.head()

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,unit,observation_date,period_start,period_end,fiscal_year,gender,location,region,source_name,source_type,source_url,confidence,related_indicator,relationship_type,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
0,REC_0001,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,22.0,NaN,percentage,%,2014-12-31,NaT,NaT,2014,all,national,NaN,Global Findex 2014,survey,https://www.worldbank.org/en/publication/globa...,high,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Baseline year,NaN
1,REC_0002,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,35.0,NaN,percentage,%,2017-12-31,NaT,NaT,2017,all,national,NaN,Global Findex 2017,survey,https://www.worldbank.org/en/publication/globa...,high,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,NaN,NaN
2,REC_0003,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,46.0,NaN,percentage,%,2021-12-31,NaT,NaT,2021,all,national,NaN,Global Findex 2021,survey,https://www.worldbank.org/en/publication/globa...,high,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,NaN,NaN
3,REC_0004,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,56.0,NaN,percentage,%,2021-12-31,NaT,NaT,2021,male,national,NaN,Global Findex 2021,survey,https://www.worldbank.org/en/publication/globa...,high,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Gender disaggregated,NaN
4,REC_0005,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,36.0,NaN,percentage,%,2021-12-31,NaT,NaT,2021,female,national,NaN,Global Findex 2021,survey,https://www.worldbank.org/en/publication/globa...,high,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Gender disaggregated,NaN

In [45]:
impact_links.head()

,record_id,parent_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,unit,observation_date,period_start,period_end,fiscal_year,gender,location,region,source_name,source_type,source_url,confidence,related_indicator,relationship_type,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
0,IMP_0001,EVT_0001,impact_link,NaN,ACCESS,Telebirr effect on Account Ownership,NaN,NaN,15.0,NaN,percentage,%,2021-05-17,NaN,NaN,NaN,all,national,NaN,NaN,NaN,NaN,medium,ACC_OWNERSHIP,direct,increase,high,15.0,12,literature,Kenya,Example_Trainee,2025-01-20,NaN,Kenya M-Pesa showed +20pp over 5 years
1,IMP_0002,EVT_0001,impact_link,NaN,USAGE,Telebirr effect on Telebirr Users,NaN,NaN,NaN,NaN,count,users,2021-05-17,NaN,NaN,NaN,all,national,NaN,NaN,NaN,NaN,high,USG_TELEBIRR_USERS,direct,increase,high,NaN,3,empirical,NaN,Example_Trainee,2025-01-20,NaN,Direct subscriber acquisition
2,IMP_0003,EVT_0001,impact_link,NaN,USAGE,Telebirr effect on P2P Transactions,NaN,NaN,25.0,NaN,percentage,%,2021-05-17,NaN,NaN,NaN,all,national,NaN,NaN,NaN,NaN,medium,USG_P2P_COUNT,direct,increase,high,25.0,6,empirical,NaN,Example_Trainee,2025-01-20,NaN,New digital payment channel
3,IMP_0004,EVT_0002,impact_link,NaN,ACCESS,Safaricom effect on 4G Coverage,NaN,NaN,15.0,NaN,percentage,%,2022-08-01,NaN,NaN,NaN,all,national,NaN,NaN,NaN,NaN,medium,ACC_4G_COV,direct,increase,medium,15.0,12,empirical,NaN,Example_Trainee,2025-01-20,NaN,Network investment from competition
4,IMP_0005,EVT_0002,impact_link,NaN,AFFORDABILITY,Safaricom effect on Data Affordability,NaN,NaN,-20.0,NaN,percentage,%,2022-08-01,NaN,NaN,NaN,all,national,NaN,NaN,NaN,NaN,medium,AFF_DATA_INCOME,indirect,decrease,medium,-20.0,12,literature,Rwanda,Example_Trainee,2025-01-20,NaN,Competition typically reduces prices

In [46]:
reference.head()

,field,code,description,applies_to
0,record_type,observation,Actual measured value from a source,All
1,record_type,event,Policy launch market event or milestone,All
2,record_type,impact_link,Relationship between event and indicator (link...,All
3,record_type,target,Policy target or official goal,All
4,record_type,baseline,Starting point for comparison,All

In [47]:
print(reference.columns.tolist())

['field', 'code', 'description', 'applies_to']

4. Understand the schema

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 34 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   record_id            43 non-null     str
 1   record_type          43 non-null     str
 2   category             10 non-null     str
 3   pillar               33 non-null     str
 4   indicator            43 non-null     str
 5   indicator_code       43 non-null     str
 6   indicator_direction  33 non-null     str
 7   value_numeric        33 non-null     float64
 8   value_text           10 non-null     str
 9   value_type           43 non-null     str
 10  unit                 33 non-null     str
 11  observation_date     43 non-null     datetime64[us]
 12  period_start         10 non-null     datetime64[us]
 13  period_end           10 non-null     datetime64[us]
 14  fiscal_year          43 non-null     object
 15  gender               43 non-null     str
 16  location             43 non-null     str
 17  region               0 non-null      float64
 18  source_name          43 non-null     str
 19  source_type          43 non-null     str
 20  source_url           31 non-null     str
 21  confidence           43 non-null     str
 22  related_indicator    0 non-null      float64
 23  relationship_type    0 non-null      float64
 24  impact_direction     0 non-null      float64
 25  impact_magnitude     0 non-null      float64
 26  impact_estimate      0 non-null      float64
 27  lag_months           0 non-null      float64
 28  evidence_basis       0 non-null      float64
 29  comparable_country   43 non-null     str
 30  collected_by         43 non-null     datetime64[us]
 31  collection_date      10 non-null     str
 32  original_text        33 non-null     str
 33  notes                0 non-null      float64
dtypes: datetime64[us](4), float64(10), object(1), str(19)
memory usage: 11.6+ KB

In [49]:
df.head()

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,unit,observation_date,period_start,period_end,fiscal_year,gender,location,region,source_name,source_type,source_url,confidence,related_indicator,relationship_type,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
0,REC_0001,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,22.0,NaN,percentage,%,2014-12-31,NaT,NaT,2014,all,national,NaN,Global Findex 2014,survey,https://www.worldbank.org/en/publication/globa...,high,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Baseline year,NaN
1,REC_0002,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,35.0,NaN,percentage,%,2017-12-31,NaT,NaT,2017,all,national,NaN,Global Findex 2017,survey,https://www.worldbank.org/en/publication/globa...,high,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,NaN,NaN
2,REC_0003,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,46.0,NaN,percentage,%,2021-12-31,NaT,NaT,2021,all,national,NaN,Global Findex 2021,survey,https://www.worldbank.org/en/publication/globa...,high,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,NaN,NaN
3,REC_0004,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,56.0,NaN,percentage,%,2021-12-31,NaT,NaT,2021,male,national,NaN,Global Findex 2021,survey,https://www.worldbank.org/en/publication/globa...,high,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Gender disaggregated,NaN
4,REC_0005,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,36.0,NaN,percentage,%,2021-12-31,NaT,NaT,2021,female,national,NaN,Global Findex 2021,survey,https://www.worldbank.org/en/publication/globa...,high,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Gender disaggregated,NaN

In [50]:
df.sample(5)

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,unit,observation_date,period_start,period_end,fiscal_year,gender,location,region,source_name,source_type,source_url,confidence,related_indicator,relationship_type,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
17,REC_0018,observation,NaN,USAGE,ATM Transaction Count,USG_ATM_COUNT,neutral,119300000.0,NaN,count,transactions,2025-07-07,2024-07-08,2025-07-07,FY2024/25,all,national,NaN,EthSwitch Annual Report,operator,https://ethswitch.com/,high,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,+26% YoY (slower than P2P),NaN
37,EVT_0005,event,policy,NaN,Foreign Exchange Liberalization,EVT_FX_REFORM,NaN,NaN,Implemented,categorical,NaN,2024-07-29,NaT,NaT,2024,all,national,NaN,NBE,regulator,NaN,high,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Birr float introduced,NaN
1,REC_0002,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,35.0,NaN,percentage,%,2017-12-31,NaT,NaT,2017,all,national,NaN,Global Findex 2017,survey,https://www.worldbank.org/en/publication/globa...,high,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,NaN,NaN
35,EVT_0003,event,product_launch,NaN,M-Pesa Ethiopia Launch,EVT_MPESA,NaN,NaN,Launched,categorical,NaN,2023-08-01,NaT,NaT,2023,all,national,NaN,Safaricom,operator,NaN,high,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Second mobile money entrant,NaN
15,REC_0016,observation,NaN,USAGE,P2P Transaction Count,USG_P2P_COUNT,higher_better,128300000.0,NaN,count,transactions,2025-07-07,2024-07-08,2025-07-07,FY2024/25,all,national,NaN,EthSwitch Annual Report,operator,https://ethswitch.com/,high,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,128.3 million P2P transactions,+158% YoY growth,NaN

In [51]:
df.describe(include="all")

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,unit,observation_date,period_start,period_end,fiscal_year,gender,location,region,source_name,source_type,source_url,confidence,related_indicator,relationship_type,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
count,43,43,10,33,43,43,33,3.300000e+01,10,43,33,43,10,10,43.0,43,43,0.0,43,43,31,43,0.0,0.0,0.0,0.0,0.0,0.0,0.0,43,43,10,33,0.0
unique,43,3,7,4,29,29,3,NaN,3,6,8,NaN,NaN,NaN,13.0,3,1,NaN,25,7,8,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,10,32,NaN
top,REC_0001,observation,product_launch,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,NaN,Launched,percentage,%,NaN,NaN,NaN,2024.0,all,national,NaN,Global Findex 2021,operator,https://www.worldbank.org/en/publication/globa...,high,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Example_Trainee,NaN,Account ownership increased from 46% to 49%,Gender disaggregated,NaN
freq,1,30,2,16,7,7,27,NaN,7,17,16,NaN,NaN,NaN,12.0,39,43,NaN,5,15,10,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43,NaN,1,2,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.437258e+10,NaN,NaN,NaN,2024-05-09 02:13:57.209302,2024-02-28 04:48:00,2025-05-08 19:12:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-20 00:00:00,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.080000e+00,NaN,NaN,NaN,2014-12-31 00:00:00,2021-09-01 00:00:00,2024-07-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-20 00:00:00,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.400000e+01,NaN,NaN,NaN,2023-07-16 00:00:00,2024-07-08 00:00:00,2025-07-01 18:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-20 00:00:00,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.140000e+01,NaN,NaN,NaN,2024-12-31 00:00:00,2024-07-08 00:00:00,2025-07-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-20 00:00:00,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.500000e+07,NaN,NaN,NaN,2025-07-07 00:00:00,2024-07-08 00:00:00,2025-07-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-20 00:00:00,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.380000e+12,NaN,NaN,NaN,2030-12-31 00:00:00,2024-10-15 00:00:00,2025-07-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-20 00:00:00,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.231061e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
print(df.columns.tolist())

['record_id', 'record_type', 'category', 'pillar', 'indicator', 'indicator_code', 'indicator_direction', 'value_numeric', 'value_text', 'value_type', 'unit', 'observation_date', 'period_start', 'period_end', 'fiscal_year', 'gender', 'location', 'region', 'source_name', 'source_type', 'source_url', 'confidence', 'related_indicator', 'relationship_type', 'impact_direction', 'impact_magnitude', 'impact_estimate', 'lag_months', 'evidence_basis', 'comparable_country', 'collected_by', 'collection_date', 'original_text', 'notes']

In [53]:
reference.head(20)

,field,code,description,applies_to
0,record_type,observation,Actual measured value from a source,All
1,record_type,event,Policy launch market event or milestone,All
2,record_type,impact_link,Relationship between event and indicator (link...,All
3,record_type,target,Policy target or official goal,All
4,record_type,baseline,Starting point for comparison,All
5,record_type,forecast,Predicted future value,All
6,category,product_launch,New product or service introduced,event
7,category,market_entry,New competitor enters market,event
8,category,market_exit,Competitor leaves market,event
9,category,policy,Government strategy or regulatory framework,event
10,category,regulation,Specific regulatory directive or rule change,event
11,category,infrastructure,System or network deployment,event
12,category,partnership,Integration or cooperation between entities,event
13,category,milestone,Achievement or threshold crossed,event
14,category,economic,Macro-economic shock or reform,event
15,category,pricing,Price or tariff change,event
16,pillar,ACCESS,Can people reach services? Coverage devices ac...,observation/target/impact_link
17,pillar,USAGE,Are people actively using? Transactions active...,observation/target/impact_link
18,pillar,QUALITY,Do services work? Success rates uptime,observation/target/impact_link
19,pillar,AFFORDABILITY,Can people afford it? Costs relative to income,observation/target/impact_link